### ISSUE TITLE
Run unit tests on Travis CI

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#102]
Depends on #101.

We need to enable codecov.io for this project.

Initial `.travis.yml` file:

```yml
language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

install:
  - true

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew clean build test jacocoTestReport check
```
